@echo off
setlocal
set "P=%TEMP%\PacmanGame.ps1"
> "%P%" echo Add-Type -AssemblyName System.Windows.Forms
>>"%P%" echo Add-Type -AssemblyName System.Drawing
>>"%P%" echo [Windows.Forms.Application]::EnableVisualStyles()
>>"%P%" echo $f=New-Object Windows.Forms.Form;$f.WindowState='Maximized';$f.FormBorderStyle='None';$f.TopMost=$true;$f.KeyPreview=$true;$f.BackColor='Black'
>>"%P%" echo $W=31;$H=21;$G=28;$m=New-Object 'char[,]' $H,$W;$s=[pscustomobject]@{x=15;y=19;dx=0;dy=0;nx=0;ny=0;score=0;lives=3;power=0;over=0;god=0;keys=''};$D=New-Object 'System.Collections.Generic.List[Drawing.Point]';$E=New-Object 'System.Collections.Generic.List[Drawing.Point]';$home=@([Drawing.Point]::new(14,9),[Drawing.Point]::new(15,9),[Drawing.Point]::new(16,9),[Drawing.Point]::new(15,10));$P=New-Object 'System.Collections.Generic.List[Drawing.Point]'
>>"%P%" echo function NewMaze{$pat=@('###############################','#........#.....#.....#........#','#.###.###.#.###.#.###.###.###','#.#.....#.#...#.#...#.#.....#','#.#.###.#.###.#.###.#.###.#.#','#...#...#.....#.....#...#...#','###.#.#####.#######.#####.#.###','#...#.....#...#...#.....#...#','#.#####.###.#.#.#.###.#####.#','#...........#...#...........#','#.#####.###.#####.###.#####.#','#...#.....#...#...#.....#...#','###.#.#####.#.#.#.#####.#.###','#...#...#...#.#.#...#...#...#','#.#.###.#.###.#.###.#.###.#.#','#.#.....#.....#.....#.....#.#','#.###.###.###.#.###.###.###.#','#.....#.....#...#.....#.....#','#.#####.###.#####.###.#####.#','#........#.....#.....#........#','###############################');for($y=0;$y-lt$H;$y++){for($x=0;$x-lt$W;$x++){$m[$y,$x]=if($pat[$y][$x]-eq'#'){'#'}else{' '}}}}
>>"%P%" echo function Open($x,$y){$x-ge0-and$x-lt$W-and$y-ge0-and$y-lt$H-and$m[$y,$x]-eq' '}
>>"%P%" echo function Reset{NewMaze;$D.Clear();$E.Clear();$P.Clear();$s.x=15;$s.y=19;$s.dx=0;$s.dy=0;$s.nx=0;$s.ny=0;$s.score=0;$s.lives=3;$s.power=0;$s.over=0;for($y=1;$y-lt20;$y++){for($x=1;$x-lt30;$x++){if((Open $x $y)-and-not($x-eq15-and$y-eq19)-and-not($x-ge13-and$x-le17-and$y-ge8-and$y-le10)){$D.Add([Drawing.Point]::new($x,$y))}}};$P.Add([Drawing.Point]::new(1,1));$P.Add([Drawing.Point]::new(29,1));$P.Add([Drawing.Point]::new(1,19));$P.Add([Drawing.Point]::new(29,19));foreach($p in $home){$E.Add([Drawing.Point]::new($p.X,$p.Y))};$t.Start();$f.Invalidate()}
>>"%P%" echo $f.Add_KeyDown({$k=$_.KeyCode;if($k-eq'Escape'){$f.Close();return};if($k-eq'R'){Reset;return};if($k-eq'W'-or$k-eq'Up'){$s.nx=0;$s.ny=-1}elseif($k-eq'S'-or$k-eq'Down'){$s.nx=0;$s.ny=1}elseif($k-eq'A'-or$k-eq'Left'){$s.nx=-1;$s.ny=0}elseif($k-eq'D'-or$k-eq'Right'){$s.nx=1;$s.ny=0};$s.keys+=([string]$k).ToLower();if($s.keys.Length-gt7){$s.keys=$s.keys.Substring($s.keys.Length-7)};if($s.keys-eq'redskia'){$s.god=1-$s.god;$s.keys=''}})
>>"%P%" echo $t=New-Object Windows.Forms.Timer;$t.Interval=110;$t.Add_Tick({if($s.over){return};if($s.power-gt0){$s.power--};$a=$s.x+$s.nx;$b=$s.y+$s.ny;if(Open $a $b){$s.dx=$s.nx;$s.dy=$s.ny;$s.nx=0;$s.ny=0};$a=$s.x+$s.dx;$b=$s.y+$s.dy;if(Open $a $b){$s.x=$a;$s.y=$b};for($i=$D.Count-1;$i-ge0;$i--){if($D[$i].X-eq$s.x-and$D[$i].Y-eq$s.y){$D.RemoveAt($i);$s.score+=10;break}};for($i=$P.Count-1;$i-ge0;$i--){if($P[$i].X-eq$s.x-and$P[$i].Y-eq$s.y){$P.RemoveAt($i);$s.score+=50;$s.power=100;$P.RemoveAt($i);break}};for($i=0;$i-lt$E.Count;$i++){$p=$E[$i];$ds=@();foreach($v in @([Drawing.Point]::new(1,0),[Drawing.Point]::new(-1,0),[Drawing.Point]::new(0,1),[Drawing.Point]::new(0,-1))){if(Open ($p.X+$v.X) ($p.Y+$v.Y)){$ds+=$v}};if($ds.Count){$v=$ds|Sort-Object {[Math]::Abs($p.X+$_.X-$s.x)+[Math]::Abs($p.Y+$_.Y-$s.y)}|Select-Object -First 1;if((Get-Random 100)-lt25){$v=$ds|Get-Random};$p.X+=$v.X;$p.Y+=$v.Y;$E[$i]=$p};if($p.X-eq$s.x-and$p.Y-eq$s.y){if($s.power){$s.score+=200;$E[$i]=[Drawing.Point]::new($home[$i].X,$home[$i].Y)}elseif(!$s.god){$s.lives--;if($s.lives-le0){$s.over=1;$t.Stop()}else{$s.x=15;$s.y=19;$s.dx=0;$s.dy=0}}}};if($D.Count-eq0){$s.over=1;$t.Stop()};$f.Invalidate()})
>>"%P%" echo $f.Add_Paint({$z=$_.Graphics;$z.Clear('Black');$ox=[int](($f.ClientSize.Width-$W*$G)/2);$oy=55;$font=[Drawing.Font]::new('Arial',18,[Drawing.FontStyle]::Bold);$z.DrawString(('SCORE: '+$s.score+'   LIVES: '+$s.lives+$(if($s.power){'   POWER!'}else{''})), $font,[Drawing.Brushes]::White,15,12);for($y=0;$y-lt$H;$y++){for($x=0;$x-lt$W;$x++){if($m[$y,$x]-eq'#'){$z.FillRectangle([Drawing.Brushes]::Blue,$ox+$x*$G,$oy+$y*$G,$G-1,$G-1)}}};foreach($d in $D){$z.FillEllipse([Drawing.Brushes]::White,$ox+$d.X*$G+10,$oy+$d.Y*$G+10,6,6)};foreach($p in $P){$z.FillEllipse([Drawing.Brushes]::Gold,$ox+$p.X*$G+7,$oy+$p.Y*$G+7,14,14)};$z.FillPie([Drawing.Brushes]::Yellow,$ox+$s.x*$G+3,$oy+$s.y*$G+3,$G-6,$G-6,35,290);$cc=@('Red','DeepPink','Cyan','Orange');for($i=0;$i-lt$E.Count;$i++){$p=$E[$i];$b=New-Object Drawing.SolidBrush([Drawing.Color]::FromName($(if($s.power){'Blue'}else{$cc[$i]})));$z.FillEllipse($b,$ox+$p.X*$G+3,$oy+$p.Y*$G+3,$G-6,$G-6);$b.Dispose()};if($s.over){$font2=[Drawing.Font]::new('Arial',52,[Drawing.FontStyle]::Bold);$msg=if($D.Count-eq0){'YOU WIN'}else{'GAME OVER - R'};$z.DrawString($msg,$font2,[Drawing.Brushes]::White,($f.ClientSize.Width-350)/2,($f.ClientSize.Height-70)/2);$font2.Dispose()};$font.Dispose()})
>>"%P%" echo Reset
>>"%P%" echo [Windows.Forms.Application]::Run($f)
powershell -NoProfile -ExecutionPolicy Bypass -File "%P%"
del "%P%" >nul 2>&1
endlocal